CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	IMG VARCHAR(300),
	CNT INT DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE
);

DROP TABLE BOARD;

SELECT * FROM BOARD;

INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(1,'����','������','����');